version: 0.0
os: linux

files:
  # 把 artifact 根（也就是 build 的 dist/shop 下文件）复制到 /var/www/html
  - source: .
    destination: /var/www/html

hooks:
  # 如果你不需要任何钩子，这一段可以省略或留空
  # AfterInstall:
  #   - location: scripts/your-post-install.sh
  #     timeout: 300
  #     runas: root