version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # 👈 强制使用 Node.js 16
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - echo npm install completed on `date`
      - npm run build  # 👈 不需要 NODE_OPTIONS 了（Node 16 不会报错）
      - echo npm run build completed on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -l ./dist/shop/

artifacts:
  files:
    - ./dist/shop/*
    - ./dist/shop/assets/*
    - appspec.yml
