version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install

  build:
    commands:
      - npm run build   # 默认调用 package.json 里的 "build": "ng build --project=shop"

  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  # 先把 appspec.yml 放进去
  files:
    - appspec.yml
  # 然后把 dist/shop 下的所有文件——平级打包到根目录下
    - '**/*'
  base-directory: dist/shop
