version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - echo "Installing..."
      - npm install
      - echo "Building Angular..."
      - npm run build            # 产出到 dist/shop
      - echo "Copying appspec and scripts..."
      - cp appspec.yml dist/shop/        # 把 appspec.yml 拷进来
      - cp -r scripts dist/shop/scripts  # 把 scripts 文件夹也拷进来
  post_build:
    commands:
      - echo "Build finished on `date`"

artifacts:
  base-directory: dist/shop     # ← 从这里开始往上打包
  files:
    - '**/*'                    # ← 包括所有静态文件 + appspec.yml + scripts 文件夹
