version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Nothing to do in pre_build...
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - npm run build -- --project=shop
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Post build contents:
      - ls -R dist/shop

artifacts:
  files:
    - appspec.yml           # ← 根目录下的 appspec.yml
    - dist/shop/**/*        # ← dist/shop 里的所有文件
