version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - echo "Install dependencies..."
      - npm install
      - echo "Build Angular..."
      - npm run build        # 产出到 dist/shop
      - cp appspec.yml dist/shop/   # ✅ 把 appspec.yml 拷进 dist/shop
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  base-directory: dist/shop    # ← 告诉 CodeBuild：从 dist/shop 开始打包
  files:
    - '**/*'                   # ← 这个就已经包含了 appspec.yml
