version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - echo "Nothing to do in pre_build phase..."

  build:
    commands:
      - echo "Build started on `date`"
      - npm install
      - npm run build

  post_build:
    commands:
      - echo "Build completed on `date`"
      - ls -l dist/shop/

artifacts:
  files:
    - appspec.yml
    - dist/shop/**/*
