version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing...
      - npm install
      - echo "Enabling legacy OpenSSL provider..."
      - export NODE_OPTIONS=--openssl-legacy-provider
  build:
    commands:
      - echo Building Angular App...
      - ./node_modules/.bin/ng build --project=shop || exit 1
      - echo Build completed.
      - ls -al dist/shop || echo "Build failed or output path incorrect!"
artifacts:
  files:
    - '**/*'
  base-directory: dist/shop
