version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "install dependencies..."
      - npm install

  build:
    commands:
      - echo "build angular app..."
      - npm run build -- --project=shop

artifacts:
  files:
    - appspec.yml          # 一定要带上
    - '**/*'               # 把 dist/shop 下的所有文件都打进去
  base-directory: dist/shop
