version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building Angular App with OpenSSL legacy provider...
      - NODE_OPTIONS=--openssl-legacy-provider npx ng build --project=shop || exit 1
      - echo Build completed.
      - ls -al dist/shop || echo "Build output not found!"
artifacts:
  files:
    - '**/*'
  base-directory: dist/shop
