version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building Angular project...
      - npm run build -- --project=shop
      - echo Build completed on `date`

artifacts:
  # 先包含 appspec.yml
  files:
    - appspec.yml
  # 再包含 dist/shop 下所有文件
    - '**/*'
  base-directory: dist/shop
