version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
      - echo "export NODE_OPTIONS=--openssl-legacy-provider" >> ~/.bashrc
      - export NODE_OPTIONS=--openssl-legacy-provider

  pre_build:
    commands:
      - echo Compiling Angular app with OpenSSL legacy provider...
      - echo "NODE_OPTIONS=$NODE_OPTIONS"
      - ./node_modules/.bin/ng build --project=shop || exit 1
      - ls -al dist/shop || echo "Build failed: dist/shop not found!"

artifacts:
  files:
    - '**/*'
  base-directory: dist/shop
