version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci

  pre_build:
    commands:
      - echo Enabling OpenSSL legacy provider...
      - export NODE_OPTIONS=--openssl-legacy-provider

  build:
    commands:
      - echo Building Angular project...
      - npm run build -- --project=shop
      - echo Listing dist/shop contents...
      - ls -al dist/shop || echo "dist/shop missing!"

artifacts:
  files:
    - '**/*'
  base-directory: dist/shop
