version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - npm install
      - npm run build
      - cp appspec.yml dist/shop/
      - cp -r scripts dist/shop/scripts    # ⬅️ scripts 目录必须存在！
artifacts:
  base-directory: dist/shop
  files:
    - '**/*'
