version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci

  build:
    commands:
      - echo Setting legacy OpenSSL provider...
      - export NODE_OPTIONS=--openssl-legacy-provider
      - echo Building Angular project...
      - npm run build -- --project=shop

artifacts:
  files:
    - '**/*'
  base-directory: dist/shop