AWSTemplateFormatVersion: '2010-09-09'
Description: Compute stack - Security Group and EC2 Instances

Parameters:
  Environment:
    Type: String
  ResourcePrefix:
    Type: String
  VpcId:
    Type: String
  Subnet1Id:
    Type: String
  Subnet2Id:
    Type: String

Conditions:
  IsPrd: !Equals [!Ref Environment, prd]

Resources:
  InstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Allow SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${ResourcePrefix}-sg'

  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId: !Ref Subnet1Id
      ImageId: ami-0f3a440bbcff3d043
      SecurityGroupIds:
        - !Ref InstanceSG
      Tags:
        - Key: Name
          Value: !Sub '${ResourcePrefix}-ec2-1'

  EC2Instance2:
    Type: AWS::EC2::Instance
    Condition: IsPrd
    Properties:
      InstanceType: t2.micro
      SubnetId: !Ref Subnet2Id
      ImageId: ami-0f3a440bbcff3d043
      SecurityGroupIds:
        - !Ref InstanceSG
      Tags:
        - Key: Name
          Value: !Sub '${ResourcePrefix}-ec2-2'
