AWSTemplateFormatVersion: '2010-09-09'
Description: Compute stack - Security Group and EC2 Instances

Parameters:
  Environment:
    Type: String
  ResourcePrefix:
    Type: String

Conditions:
  IsPrd:
    Fn::Equals:
      - Ref: Environment
      - prd

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${Environment}-VpcId"
      GroupDescription: Allow SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ResourcePrefix}-sg"

  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: "${Environment}-Subnet1Id"
      ImageId: ami-0f3a440bbcff3d043
      SecurityGroupIds:
        - Ref: MySecurityGroup
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ResourcePrefix}-ec2-1"

  EC2Instance2:
    Type: AWS::EC2::Instance
    Condition: IsPrd
    Properties:
      InstanceType: t2.micro
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: "${Environment}-Subnet2Id"
      ImageId: ami-0f3a440bbcff3d043
      SecurityGroupIds:
        - Ref: MySecurityGroup
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ResourcePrefix}-ec2-2"
