AWSTemplateFormatVersion: '2010-09-09'
Description: VPC with two subnets, 随机一个子网仅在 prd 环境创建

Mappings:
  env:
    "111111111111":
      name: dev
      vpc: 10.0.0.0/16
      subnet1a: 10.0.0.0/24
      subnet1c: 10.0.1.0/24
    "325216836291":
      name: stg
      vpc: 10.1.0.0/16
      subnet1a: 10.1.0.0/24
      subnet1c: 10.1.1.0/24
    "999999999999":
      name: prd
      vpc: 10.2.0.0/16
      subnet1a: 10.2.0.0/24
      subnet1c: 10.2.1.0/24

Conditions:
  IsPrdAccount: !Equals
    - !FindInMap [env, !Ref "AWS::AccountId", name]
    - prd

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !FindInMap
        - env
        - !Ref "AWS::AccountId"
        - vpc
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::AccountId}-vpc"

  Subnet1a:
    Type: AWS::EC2::Subnet
    Condition: IsPrdAccount
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !FindInMap
        - env
        - !Ref "AWS::AccountId"
        - subnet1a
      AvailabilityZone: !Sub "${AWS::Region}a"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::AccountId}-subnet1a"

  Subnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !FindInMap
        - env
        - !Ref "AWS::AccountId"
        - subnet1c
      AvailabilityZone: !Sub "${AWS::Region}c"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::AccountId}-subnet1c"
