AWSTemplateFormatVersion: '2010-09-09'
Description: 创建一个位于已存在子网中的 EC2 实例

Parameters:
  EnvType:
    Type: String
    Default: dev
    AllowedValues: [dev, stg, prd]
    Description: 环境类型

Mappings:
  InstanceTypeMap:
    dev:
      InstanceType: t2.micro
    stg:
      InstanceType: t3.micro
    prd:
      InstanceType: t3.small

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [InstanceTypeMap, !Ref EnvType, InstanceType]
      ImageId: ami-0c3fd0f5d33134a76  # Amazon Linux 2 (东京区域)
      SubnetId: !ImportValue dev-Subnet1aId  # 注意根据 EnvType 切换
      Tags:
        - Key: Name
          Value: !Sub "${EnvType}-EC2"
