AWSTemplateFormatVersion: '2010-09-09'
Description: 创建一个 VPC 和两个子网（分别位于 1a 和 1c）

Parameters:
  EnvType:
    Type: String
    Default: dev
    AllowedValues: [dev, stg, prd]
    Description: 环境类型

Mappings:
  VpcCidrMap:
    dev:
      CidrBlock: 10.0.0.0/16
    stg:
      CidrBlock: 10.1.0.0/16
    prd:
      CidrBlock: 10.2.0.0/16

  SubnetCidrMap:
    dev:
      Subnet1a: 10.0.1.0/24
      Subnet1c: 10.0.2.0/24
    stg:
      Subnet1a: 10.1.1.0/24
      Subnet1c: 10.1.2.0/24
    prd:
      Subnet1a: 10.2.1.0/24
      Subnet1c: 10.2.2.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !FindInMap [VpcCidrMap, !Ref EnvType, CidrBlock]
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${EnvType}-VPC"

  Subnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Sub "${AWS::Region}a"
      CidrBlock: !FindInMap [SubnetCidrMap, !Ref EnvType, Subnet1a]
      Tags:
        - Key: Name
          Value: !Sub "${EnvType}-Subnet-1a"

  Subnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Sub "${AWS::Region}c"
      CidrBlock: !FindInMap [SubnetCidrMap, !Ref EnvType, Subnet1c]
      Tags:
        - Key: Name
          Value: !Sub "${EnvType}-Subnet-1c"

Outputs:
  Subnet1aId:
    Value: !Ref Subnet1a
    Export:
      Name: !Sub "${EnvType}-Subnet1aId"

  Subnet1cId:
    Value: !Ref Subnet1c
    Export:
      Name: !Sub "${EnvType}-Subnet1cId"
